preserve_hierarchy: true
# The next line restricts exported languages to those actively being translated.
"export_languages": {
                      "az",
                      "de",
                      "es-ES",
                      "fr",
                      "pt-PT",
                      "ru"
}

files:
- source: /src/main/resources/*.properties
  translation: /src/main/resources/crowdin/%file_name%_%osx_locale%.%file_extension%
  ignore:
  - '*_??.properties'
  - log4j.properties
  type: properties
  escape_quotes: 0
  update_option: update_as_unapproved
  languages_mapping:
    osx_locale:
      zh-CN: zh_CN
      zh-TW: zh_TW
