preserve_hierarchy: true
"export_languages": [
    "de",
    "es-ES",
    "fr",
    "pt-PT"
]


files:
  - source: /src/main/resources/*.properties
    translation: >-
      /src/main/resources/crowdin/%file_name%_%osx_locale%.%file_extension%
    ignore:
      - '*_??.properties'
      - log4j.properties
    type: properties
    escape_quotes: 0
    update_option: update_as_unapproved
    languages_mapping:
      osx_locale:
        zh-CN: zh_CN
        zh-TW: zh_TW
